name: Accept Host Key
  run: ssh-keyscan -H yec2-18-116-99-125.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts



name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          scp -r * ec2-user@ec2-18-116-99-125.us-east-2.compute.amazonaws.com:/home/ec2-user/portfolio/
